// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpd7A_D-7h0ALkIxcVKtLR0cYB1w-j5wU',
    appId: '1:891211650354:web:92c12fa5036dc3817cb32b',
    messagingSenderId: '891211650354',
    projectId: 'notes-5cee9',
    authDomain: 'notes-5cee9.firebaseapp.com',
    storageBucket: 'notes-5cee9.firebasestorage.app',
    measurementId: 'G-DXQC0NEEV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7JqkWVwJjD9eGg1DfXV-oD2PSOn0WuZc',
    appId: '1:891211650354:android:092442e6860e19617cb32b',
    messagingSenderId: '891211650354',
    projectId: 'notes-5cee9',
    storageBucket: 'notes-5cee9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy_n3AEVRCQrfZzDLNqaUL1tLf6p6uZX4',
    appId: '1:891211650354:ios:a1d7072fcc1ba9107cb32b',
    messagingSenderId: '891211650354',
    projectId: 'notes-5cee9',
    storageBucket: 'notes-5cee9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy_n3AEVRCQrfZzDLNqaUL1tLf6p6uZX4',
    appId: '1:891211650354:ios:a1d7072fcc1ba9107cb32b',
    messagingSenderId: '891211650354',
    projectId: 'notes-5cee9',
    storageBucket: 'notes-5cee9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpd7A_D-7h0ALkIxcVKtLR0cYB1w-j5wU',
    appId: '1:891211650354:web:1f71bb9e5f3d4c107cb32b',
    messagingSenderId: '891211650354',
    projectId: 'notes-5cee9',
    authDomain: 'notes-5cee9.firebaseapp.com',
    storageBucket: 'notes-5cee9.firebasestorage.app',
    measurementId: 'G-2PJ5T3BRVW',
  );
}
